steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/signvrse-website:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/signvrse-website:latest'
      - '--build-arg'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/signvrse-website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/signvrse-website:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'signvrse-website'
      - '--image'
      - 'gcr.io/$PROJECT_ID/signvrse-website:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'terp-animations@signvrse.iam.gserviceaccount.com'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--cpu-boost'
      - '--no-cpu-throttling'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/signvrse-website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/signvrse-website:latest'

# Substitution variables (can be overridden at build time)
substitutions:
  _GEMINI_API_KEY: ''

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
